#!/usr/bin/env node
// Unified data CLI — a thin orchestrator over the numbered pipeline scripts in
// this folder (see README.md → "Data pipeline"). It never re-implements fetching
// or image work; it just runs the existing steps in the right order with the right
// flags, and preserves the hand-curated override files (package-shapes.json,
// flap-*.json, bare-meta-patch.json, cyl-src/…) by only ever re-APPLYING them.
//
//   npm run data -- <command> [options]
//   node scripts/cli.js <command> [options]
//
// Commands:
//   refresh                 Re-fetch BGG data for ALL games, re-enrich, rebuild assets
//     --since=<YYYY>         …only games published in/after that year
//     --last-year            …only games published in the last ~12 months
//     --last-month           …only games published this calendar year
//                            (BGG publish data is year-granular, so "month" == this year)
//   add                     Pull newly-added games from Airtable and process only the new ones
//   assets                  Re-run the offline generators/overlays only (no network):
//                           shapes, flaps, alt-titles, bare-meta, salmon cutout, chip-bag model
//   help                    Show this help
//
// Global options:
//   --dry-run               Print the plan; run nothing
//   --force-bgg             (refresh) delete the cached BGG JSON first so data is truly re-fetched
//
// Network steps (1, 3, 4, 8) drive a headless Chromium / hit BGG + Airtable; run
//   `npx playwright install chromium` once beforehand.
const { spawnSync } = require('child_process');
const { fs, path, ROOT, loadGames } = require('./lib');
const NODE = process.execPath;
const CACHE = path.join(__dirname, 'bgg-cache');

const argv = process.argv.slice(2);
const cmd = argv.find((a) => !a.startsWith('--')) || 'help';
const has = (f) => argv.includes(f);
const opt = (f) => { const a = argv.find((x) => x.startsWith(f + '=')); return a ? a.slice(f.length + 1) : null; };
const DRY = has('--dry-run');

function step(label, script, args = []) {
  console.log(`\n▶ ${label}\n  node scripts/${script} ${args.join(' ')}`.trimEnd());
  if (DRY) return;
  const r = spawnSync(NODE, [path.join(__dirname, script), ...args], { cwd: ROOT, stdio: 'inherit' });
  if (r.status !== 0) { console.error(`✗ ${script} exited ${r.status}`); process.exit(r.status || 1); }
}

// The offline "cleanups we've built": re-apply hand-curated overlays + regenerate
// the bespoke package assets. All deterministic, no network. Vision-audit-driven
// steps (12/13/14/20/21) are intentionally excluded — they need the gitignored
// _fronts/_flaps/_artcrop/_backquads caches and are run manually.
function assets() {
  step('Apply package shapes (tins, bags, models)', '16-apply-shapes.js', ['--apply']);
  step('Apply flap geometry', 'measure-flaps.js');
  step('Apply alternate titles', '17-alt-titles.js', ['--apply']);
  step('Backfill metadata for non-BGG games', 'enrich-bare.js', ['--apply']);
  step('Cylinder (tin/tube) wrap textures', '18-cyl-textures.js', ['--apply']);
  step('Happy Salmon fish-pouch cutout', 'gen-salmon-cutout.js');
  step('Bag of Chips model atlas', 'gen-chipbag-atlas.js');
  step('Bake Bag of Chips GLB', 'bake-chipbag-glb.js');
  console.log('\n✓ assets rebuilt. (Social OG cards are generated by `npm run build`.)');
}

function idsFor(sinceYear) {
  const { list } = loadGames();
  const sel = list.filter((g) => g.year != null && g.year >= sinceYear);
  return sel;
}

function refresh() {
  const now = new Date().getFullYear();
  let sinceYear = null;
  if (opt('--since')) sinceYear = Number(opt('--since'));
  else if (has('--last-year')) sinceYear = now - 1;
  else if (has('--last-month')) sinceYear = now; // year-granular data → "this year"

  let targets = null;
  if (sinceYear != null) {
    targets = idsFor(sinceYear);
    console.log(`Refreshing ${targets.length} game(s) published in/after ${sinceYear}.`);
  } else {
    console.log('Refreshing ALL games.');
  }

  if (has('--force-bgg')) {
    const drop = (targets || loadGames().list).filter((g) => g.bggId).map((g) => path.join(CACHE, g.bggId + '.json'));
    console.log(`\n▶ Clearing ${drop.length} cached BGG record(s) to force re-fetch`);
    if (!DRY) for (const f of drop) fs.existsSync(f) && fs.unlinkSync(f);
  }

  step('Fetch BGG data (uncached games)', '4-fetch-bgg.js');   // needs Chromium
  step('Enrich games.json from BGG cache', '5-enrich.js');
  assets();
}

function add() {
  console.log('Syncing the collection from Airtable and processing newly-added games.\n');
  const before = new Set(loadGames().list.map((g) => g.id));
  step('Fetch Airtable collection', '1-fetch-airtable.js');    // needs Chromium
  step('Build game records', '2-build-games.js');
  step('Download covers', '3-download-covers.js');
  const after = loadGames().list;
  const fresh = DRY ? [] : after.filter((g) => !before.has(g.id));
  console.log(`\nNew games: ${DRY ? '(dry-run)' : fresh.length ? fresh.map((g) => g.id).join(', ') : 'none'}`);
  step('Fetch BGG data', '4-fetch-bgg.js');
  step('Enrich', '5-enrich.js');
  step('Prepare cover/thumb textures', '6-prepare-textures.js');
  const idsArg = fresh.length ? ['--ids', fresh.map((g) => g.id).join(',')] : [];
  step('Fetch box-photo galleries', 'run-all.js', ['--fetch', ...idsArg]);
  step('Build box faces', 'run-all.js', ['--build', ...idsArg]);
  assets();
}

const HELP = `Board-games data CLI — orchestrates the numbered pipeline scripts.

  npm run data -- <command> [options]

Commands:
  refresh                 Re-fetch BGG data for ALL games, re-enrich, rebuild assets
    --since=<YYYY>          …only games published in/after that year
    --last-year             …only games published in the last ~12 months
    --last-month            …only games published this calendar year (data is year-granular)
    --force-bgg             delete cached BGG JSON first so data is truly re-fetched
  add                     Pull newly-added games from Airtable, process only the new ones
  assets                  Re-run offline generators/overlays only — no network
                          (shapes, flaps, alt-titles, bare-meta, cyl, salmon, chip-bag)
  help                    Show this help

  --dry-run               Print the plan without running anything

Network steps drive headless Chromium; run \`npx playwright install chromium\` first.
Social OG preview cards are generated by \`npm run build\` (scripts/gen-og.js).`;

switch (cmd) {
  case 'refresh': refresh(); break;
  case 'add': case 'sync': add(); break;
  case 'assets': case 'cleanups': assets(); break;
  default: console.log(HELP);
}
